"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { createHash } = require("node:crypto");
const { spawnSync } = require("node:child_process");

test("initial stage-selective instance can prepare and read a current professional review draft", t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "yss-review-distribution-")), target = path.join(root, "project");
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const cli = path.resolve(__dirname, "../bin/create-yss-spec.js");
  const invoke = (entry, args, cwd = target) => spawnSync(process.execPath, [entry, ...args], { cwd, encoding: "utf8" });
  const init = invoke(cli, ["--project-name", "Review distribution", "--business-domain", "Demo", "--agent-runtime", "codex", "--target-dir", target], root);
  assert.equal(init.status, 0, init.stderr);
  const metadata = JSON.parse(fs.readFileSync(path.join(target, ".yss-template.json")));
  assert.deepEqual(metadata.distribution.installedStages, ["stage.entry-triage", "stage.plan"]);
  assert.ok(fs.existsSync(path.join(target, ".template-spec/templates/review-bundle-template.yaml")));
  const hash = bytes => createHash("sha256").update(bytes).digest("hex");
  const base = "docs/.scratch/review-distribution", cpRef = base + "/checkpoint.json";
  const write = (ref, value) => { fs.mkdirSync(path.dirname(path.join(target, ref)), { recursive: true }); fs.writeFileSync(path.join(target, ref), value); };
  const boundary = "check.domain-strategy-approved", subject = base + "/subject.json", evidence = base + "/evidence.txt";
  write(evidence, "Synthetic current review input\n"); write(subject, JSON.stringify({ fixture: true }));
  const checkpoint = JSON.parse(fs.readFileSync(path.join(target, ".template-spec/process/templates/lifecycle-checkpoint-template.json")));
  Object.assign(checkpoint, { feature_id: "feature.review-distribution", stage: "stage.plan", next_work_unit: "work-unit.plan-requirements", checks: { [boundary]: { applicable: true, status: "pending", subject_ref: subject, subject_digest: hash(fs.readFileSync(path.join(target, subject))), approval_scope: ["feature.review-distribution"], drafter_principal_ref: "fixture:author", basis: [{ ref: evidence, digest: hash(fs.readFileSync(path.join(target, evidence))) }], evidence_refs: [evidence] }, "check.stage-decision-package-approved": { applicable: false, status: "not-applicable", reason: "Synthetic test only: no stage-decision impact" } } });
  checkpoint.stage_trace.stage = "stage.plan";
  write(cpRef, JSON.stringify(checkpoint));
  const trackingItems = base + "/tracking-items.json", trackingPlan = base + "/tracking-plan.json";
  write(trackingItems, JSON.stringify([{ id: "plan-review", title: "合成 Plan 审查", stage: "stage.plan", work_unit: "work-unit.plan-requirements", owner: "fixture:owner", scope: "仅测试当前 Plan 审查分发", acceptance: ["待审任务可核验且不授予批准"], source_refs: [evidence] }]));
  const tracking = invoke(path.join(target, "scripts/stage-tracking"), ["plan", "--root", target, "--checkpoint", cpRef, "--items", trackingItems]);
  assert.equal(tracking.status, 0, tracking.stderr);
  write(trackingPlan, tracking.stdout);
  const appliedTracking = invoke(path.join(target, "scripts/stage-tracking"), ["apply", "--root", target, "--plan", path.join(target, trackingPlan)]);
  assert.equal(appliedTracking.status, 0, appliedTracking.stderr);
  const origin = base + "/origin-checkpoint.json", input = base + "/init.json";
  write(origin, fs.readFileSync(path.join(target, cpRef)));
  write(input, JSON.stringify({ feature_id: checkpoint.feature_id, scope_ids: [checkpoint.feature_id], scope_digest: hash(fs.readFileSync(path.join(target, evidence))), provenance: { kind: "new-feature", source_ref: origin, source_digest: hash(fs.readFileSync(path.join(target, origin))) } }));
  const initialized = invoke(path.join(target, "scripts/plan-review-control"), ["init", "--root", target, "--checkpoint", cpRef, "--input", input]);
  assert.equal(initialized.status, 0, initialized.stderr);
  const result = invoke(path.join(target, "scripts/prepare-review-package"), ["--root", target, "--checkpoint", cpRef, "--check", boundary, "--role", "role.product-manager", "--actor", "fixture.reviewer", "--reviewer-principal", "fixture:reviewer", "--drafter-principal", "fixture:packet-owner", "--implementation-actor", "fixture.worker", "--task-id", "fixture.review", "--review-session", "fixture:session", "--work-unit", "work-unit.plan-requirements", "--review-phase", "initial", "--output-dir", base + "/review"]);
  assert.equal(result.status, 0, result.stderr);
  const prepared = JSON.parse(result.stdout);
  assert.equal(prepared.decision, "pending"); assert.equal(prepared.execution_authorization, "not-granted");
  assert.equal(JSON.parse(fs.readFileSync(path.join(target, cpRef))).plan_review_control.attempts.length, 1);
  const task = invoke(path.join(target, "scripts/verify-digital-human-task-package"), [path.join(target, prepared.task_ref)]);
  assert.equal(task.status, 0, task.stderr);
  const record = path.join(target, prepared.bundle_ref), reader = path.join(target, "scripts/verify-approval-record");
  const history = invoke(reader, ["--history", record]);
  assert.equal(history.status, 0, history.stderr); assert.match(history.stdout, /execution_authorization=not-evaluated/);
  const current = invoke(reader, ["--require-approved", record]);
  assert.equal(current.status, 1); assert.match(current.stderr, /APPROVAL_CURRENT_INVALID.*decision.*approved/);
});
